config/routes.rb
Stock2::Application.routes.draw do
  root :to => "home#index"

  resources :signals
  resources :firms
  resources :day_candles
  resources :orders
  resources :daily_stocks
  resources :stock_codes do
    collection  do
      delete 'destroy_multiple'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :number_of_stocks

  belongs_to :trading_signal
  belongs_to :asset_account
  belongs_to :entry_day_candle, :class_name => DayCandle
  belongs_to :exit_day_candle, :class_name => DayCandle
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :json, :html

  def index
    #@orders = Order.all
    @orders = []
    @sum_of_earning = 0
    Order.find_each do |order|
      signal = order.trading_signal
      stock_code = signal.stock_code
      stock_code_name = stock_code.name
      stock_code_symbol = stock_code.symbol

      number_of_stocks = order.number_of_stocks
      entry_day_candle = order.entry_day_candle
      exit_day_candle = order.exit_day_candle

      @sum_of_earning +=  number_of_stocks * (exit_day_candle.o - entry_day_candle.o) * 0.99 # 슬리피지 1%

      @orders.push({"asset_strategy_name" => order.asset_account.asset_strategy.name, "stock_code_name" => stock_code_name, "stock_code_symbol" => stock_code_symbol,
               "entry_date" => entry_day_candle.date, "exit_date" => exit_day_candle.date,
               "entry_market_price" => entry_day_candle.o, "exit_market_price" => exit_day_candle.o})
    end

    respond_with(@orders)
  end

  def show
    @orders = []
    asset_account_id = params[:id]
    AssetAccount.find(asset_account_id).orders.find_each do |order|
      signal = order.trading_signal
      stock_code = signal.stock_code
      stock_code_name = stock_code.name
      stock_code_symbol = stock_code.symbol

      entry_day_candle = order.entry_day_candle
      exit_day_candle = order.exit_day_candle

      @orders.push({"asset_strategy_name" => order.asset_account.asset_strategy.name, "stock_code_name" => stock_code_name, "stock_code_symbol" => stock_code_symbol,
                    "entry_date" => entry_day_candle.date, "exit_date" => exit_day_candle.date,
                    "entry_market_price" => entry_day_candle.o, "exit_market_price" => exit_day_candle.o})
    end

    respond_with(@orders)

  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <h4 class="heading">벤자민 그레이엄</h4>
    <h5>총수익 : <%= @sum_of_earning %>원</h5>

    <table class="table table-striped" data-provides="rowlink">
      <thead>
      <tr>
        <th>자산 전략 이름</th>
        <th>종목이름</th>
        <th>종목코드</th>
        <th>진입일</th>
        <th>진입금액</th>
        <th>이탈일</th>
        <th>이탈금액</th>
        <th>수익률(세후)</th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order['asset_strategy_name'] %></td>
        <td><%= order['stock_code_name'] %></td>
        <td><%= link_to(order['stock_code_symbol'],firm_path(order['stock_code_symbol'])) %></td>
        <td><%= order['entry_date'] %></td>
        <td><%= order['entry_market_price'] %></td>
        <td><%= order['exit_date'] %></td>
        <td><%= order['exit_market_price'] %></td>
        <% earning_ratio = (order['exit_market_price'].to_f - order['entry_market_price'].to_f) / order['entry_market_price'].to_f * 100
           if earning_ratio > 0
             spanclass = "high"
             iclass = "icon-arrow-up"
           else
             spanclass = "low"
             iclass = "icon-arrow-down"
           end
        %>
            <td><span class="<%= spanclass %>"><i class="<%= iclass %>"></i><%= earning_ratio.round(3) %>%</span></td>
      </tr>

      <% end %>
      </tbody>
  </table>
  </div>
</div>

app/views/orders/show.erb
<div class="row-fluid">
  <div class="span12">
    <h4 class="heading"><%= AssetAccount.find(params[:id]).trading_strategy.name %> 의 전략</h4>
    <table class="table table-striped" data-provides="rowlink">
      <thead>
      <tr>
        <th>자산 전략 이름</th>
        <th>종목이름</th>
        <th>종목코드</th>
        <th>진입일</th>
        <th>진입금액</th>
        <th>이탈일</th>
        <th>이탈금액</th>
        <th>수익률(세후)</th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
          <tr>
            <td><%= order['asset_strategy_name'] %></td>
            <td><%= order['stock_code_name'] %></td>
            <td><%= link_to(order['stock_code_symbol'],firm_path(order['stock_code_symbol'])) %></td>
            <td><%= order['entry_date'] %></td>
            <td><%= order['entry_market_price'] %></td>
            <td><%= order['exit_date'] %></td>
            <td><%= order['exit_market_price'] %></td>
            <% earning_ratio = (order['exit_market_price'].to_f - order['entry_market_price'].to_f) / order['entry_market_price'].to_f * 100
               if earning_ratio > 0
                 spanclass = "high"
                 iclass = "icon-arrow-up"
               else
                 spanclass = "low"
                 iclass = "icon-arrow-down"
               end
            %>
            <td><span class="<%= spanclass %>"><i class="<%= iclass %>"></i><%= earning_ratio.round(3) %>%</span></td>
          </tr>

      <% end %>
  </div>
</div>