config/routes.rb
Stock2::Application.routes.draw do
  root :to => "home#index"

  resources :signals
  resources :firms
  resources :day_candles
  resources :orders
  resources :daily_stocks
  resources :stock_codes do
    collection  do
      delete 'destroy_multiple'
    end
  end

end

app/models/stock_code.rb
class StockCode < ActiveRecord::Base
  attr_accessible :issue_code, :symbol, :name, :eng_name, :standard_code, :short_code, :market_type, :crawl_date

  def self.duplicated? symbol
    self.where(:symbol => symbol).exists?
  end

  has_many :day_candles, :primary_key => :symbol, :foreign_key => :symbol
  has_many :firm_data
  has_many :trading_signals
end

app/models/stock_codes.rb
class StockCodes < ActiveRecord::Base
  attr_accessible :issue_code, :symbol, :name, :eng_name, :standard_code, :short_code, :market_type, :crawl_date

  def self.duplicated? symbol
    self.where(:symbol => symbol).exists?
  end
end

app/controllers/stock_codes_controller.rb
class StockCodesController < ApplicationController
  def index
    @stock_codes = StockCode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stock_codes }
    end
  end

  def destroy_multiple
    if params[:stock_code_ids]
      @stock_codes = StockCode.find(params[:stock_code_ids])
      @stock_codes.each do |stock_code|
        stock_code.destroy
      end
    end

    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_to stock_codes_url }
    end
  end
end

app/helpers/stock_codes_helper.rb
module StockCodesHelper
end

app/views/stock_codes/index.html.erb
<h1>Stock Codes</h1>

<%= form_tag destroy_multiple_stock_codes_path, :method => :delete do %>
<table style="width: 100%; text-align: center;">
  <tr>
    <th>이름</th>
    <th>영문이름</th>
    <th>종목코드</th>
    <th>삭제</th>
  </tr>

  <% @stock_codes.each do |stock_code| %>
      <tr>
        <td><%= stock_code.name %></td>
        <td><%= stock_code.eng_name %></td>
        <td><%= stock_code.symbol %></td>
        <td><%= check_box_tag "stock_code_ids[]", stock_code.id %></td>
      </tr>
  <% end %>
</table>
<%= submit_tag "체크된 항목들 제거" %>
<% end %>
<br />